/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.programacion_bcd.taller.vista;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 * @author confaa
 */
public class JPanelDialogCorrecto extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDialog
     */
    public JPanelDialogCorrecto() {
        initComponents();
        jLabelNombre.setText(
                Main.elector.getNombre() + " " + Main.elector.getApellido());
        jLabelDni.setText("DNI" + " " + Main.elector.getDni());
        jLabelDomicilio.setText(
                Main.elector.getDomicilio().getProvincia() + " - "
                + Main.elector.getDomicilio().getDepartamento() + " - "
                + Main.elector.getDomicilio().getLocalidad() + " - "
                + Main.elector.getDomicilio().getDireccion());
        jLabelMesa.setText("Mesa: " + Main.elector.getMesa().getNumero());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPregunta = new javax.swing.JLabel();
        jButtonRechazar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabelMesa = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();

        jLabelPregunta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelPregunta.setHorizontalAlignment(
                javax.swing.SwingConstants.CENTER);
        jLabelPregunta.setText("Estos datos son correctos?");

        jButtonRechazar.setText("Rechazar");
        jButtonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechazarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLayeredPane1.setToolTipText("");

        jLabelMesa.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabelMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMesa.setText("jLabelMesa");
        jLabelMesa.setToolTipText("");
        jLabelMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelDomicilio.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabelDomicilio.setHorizontalAlignment(
                javax.swing.SwingConstants.CENTER);
        jLabelDomicilio.setText("jLabelDomicilio");
        jLabelDomicilio.setToolTipText("");
        jLabelDomicilio.setHorizontalTextPosition(
                javax.swing.SwingConstants.CENTER);

        jLabelDni.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDni.setText("jLabelDni");
        jLabelDni.setToolTipText("");
        jLabelDni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNombre.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("jLabelNombre");
        jLabelNombre.setToolTipText("");
        jLabelNombre.setHorizontalTextPosition(
                javax.swing.SwingConstants.CENTER);

        jLayeredPane1.setLayer(jLabelMesa,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelDomicilio,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelDni,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelNombre,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(
                jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane1Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(
                                                                  jLabelMesa,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  Short.MAX_VALUE)
                                                          .addGroup(
                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                  jLayeredPane1Layout.createSequentialGroup()
                                                                          .addGroup(
                                                                                  jLayeredPane1Layout.createParallelGroup(
                                                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                                                          .addComponent(
                                                                                                  jLabelDomicilio,
                                                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                  Short.MAX_VALUE)
                                                                                          .addComponent(
                                                                                                  jLabelDni,
                                                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                  Short.MAX_VALUE))
                                                                          .addContainerGap())
                                                          .addComponent(
                                                                  jLabelNombre,
                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelNombre)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jLabelDni)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jLabelDomicilio)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jLabelMesa)
                                          .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                          .addGap(34, 34, 34)
                                          .addGroup(layout.createParallelGroup(
                                                          javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(
                                                                    jLabelPregunta,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE)
                                                            .addComponent(
                                                                    jLayeredPane1,
                                                                    javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(
                                                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                                                    layout.createSequentialGroup()
                                                                            .addComponent(
                                                                                    jButtonRechazar)
                                                                            .addPreferredGap(
                                                                                    javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                    249,
                                                                                    Short.MAX_VALUE)
                                                                            .addComponent(
                                                                                    jButtonAceptar)))
                                          .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  layout.createSequentialGroup()
                                          .addGap(45, 45, 45)
                                          .addComponent(jLayeredPane1)
                                          .addGap(46, 46, 46)
                                          .addComponent(jLabelPregunta)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                  63, Short.MAX_VALUE)
                                          .addGroup(layout.createParallelGroup(
                                                          javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(
                                                                    jButtonRechazar)
                                                            .addComponent(
                                                                    jButtonAceptar))
                                          .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:

        Votacion votacion = new Votacion();
        votacion.setVisible(true);
        Window w = SwingUtilities.getWindowAncestor(JPanelDialogCorrecto.this);
        w.setVisible(false);

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonRechazarActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechazarActionPerformed
        // TODO add your handling code here:

        Main main = new Main();
        main.setVisible(true);
        Window w = SwingUtilities.getWindowAncestor(JPanelDialogCorrecto.this);
        w.setVisible(false);
    }//GEN-LAST:event_jButtonRechazarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonRechazar;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPregunta;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
