/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.programacion_bcd.taller.vista;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 * @author confaa
 */
public class JPanelDialogErrorPersona extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDialog
     */
    public JPanelDialogErrorPersona() {
        initComponents();
        jLabelErrorPersona.setText("Persona no encontrada");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelErrorPersona = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButtonAceptar = new javax.swing.JButton();

        jLabelErrorPersona.setFont(
                new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelErrorPersona.setHorizontalAlignment(
                javax.swing.SwingConstants.CENTER);
        jLabelErrorPersona.setText("Persona no encontrada");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setHorizontalTextPosition(
                javax.swing.SwingConstants.CENTER);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jButtonAceptar,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(
                jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
                jLayeredPane2Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jButtonAceptar)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
                jLayeredPane2Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAceptar,
                                      javax.swing.GroupLayout.Alignment.TRAILING,
                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                      Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane2,
                                      javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelErrorPersona,
                                      javax.swing.GroupLayout.Alignment.TRAILING,
                                      javax.swing.GroupLayout.DEFAULT_SIZE, 500,
                                      Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  layout.createSequentialGroup()
                                          .addContainerGap(130, Short.MAX_VALUE)
                                          .addComponent(jLabelErrorPersona)
                                          .addGap(123, 123, 123)
                                          .addComponent(jLayeredPane2,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);

        Window w = SwingUtilities.getWindowAncestor(
                JPanelDialogErrorPersona.this);
        w.setVisible(false);

        Main main = new Main();
        main.setVisible(true);

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelErrorPersona;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
