/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.programacion_bcd.taller.vista;

import com.programacion_bcd.taller.sistema.Elector;
import com.programacion_bcd.taller.sistema.Lista;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author confaa
 */
public class Votacion extends javax.swing.JFrame {

    public static List<Lista> listasVotante;

    /**
     * Creates new form Votacion
     */
    public Votacion() {
        initComponents();
        this.setLocationRelativeTo(null);

        Main mainApp = new Main();
        listasVotante = traerListasVotante(Main.elector);

        jLabelVotacionProvincia.setText(
                jLabelVotacionProvincia.getText() + " "
                + Main.elector.getDomicilio().getProvincia());
        jLabelPartidoDD.setText("Derecha");
        jLabelPartidoSD.setText("Derecha");
        jLabelPartidoDI.setText("Izquierda");
        jLabelPartidoSI.setText("Izquierda");

        for (int i = 0; i < 2; i++) {
            Lista auxLista = listasVotante.get(i);
            DefaultListModel defaultListModel1 = new DefaultListModel();
            for (int j = 0; j < auxLista.getDiputados().size(); j++) {
                defaultListModel1.addElement(
                        auxLista.getDiputados().get(j).getApellido()
                        + ", "
                        + auxLista.getDiputados().get(j).getNombre());

            }

            DefaultListModel defaultListModel2 = new DefaultListModel();
            for (int j = 0; j < auxLista.getSenadores().size(); j++) {
                defaultListModel2.addElement(
                        auxLista.getSenadores().get(j).getApellido()
                        + ", "
                        + auxLista.getSenadores().get(j).getNombre());

            }

            if (auxLista.getPartido().getNombre().equals("Derecha")) {
                jRadioButtonDD.setText(auxLista.getNombreLista());
                jRadioButtonSD.setText(auxLista.getNombreLista());
                jListDD.setModel(defaultListModel1);
                jListSD.setModel(defaultListModel2);

            } else {
                jRadioButtonDI.setText(auxLista.getNombreLista());
                jRadioButtonSI.setText(auxLista.getNombreLista());
                jListDI.setModel(defaultListModel1);
                jListSI.setModel(defaultListModel2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenuVotacion = new javax.swing.JTabbedPane();
        jPanelDiputados = new javax.swing.JPanel();
        jLayeredPaneDiputados = new javax.swing.JLayeredPane();
        jRadioButtonDD = new javax.swing.JRadioButton();
        jRadioButtonDI = new javax.swing.JRadioButton();
        jScrollPaneDD = new javax.swing.JScrollPane();
        jListDD = new javax.swing.JList<>();
        jScrollPaneDI = new javax.swing.JScrollPane();
        jListDI = new javax.swing.JList<>();
        jLabelPartidoDD = new javax.swing.JLabel();
        jLabelPartidoDI = new javax.swing.JLabel();
        jPanelSenadores = new javax.swing.JPanel();
        jLayeredPaneSenadores = new javax.swing.JLayeredPane();
        jRadioButtonSD = new javax.swing.JRadioButton();
        jRadioButtonSI = new javax.swing.JRadioButton();
        jScrollPaneSD = new javax.swing.JScrollPane();
        jListSD = new javax.swing.JList<>();
        jScrollPaneSI = new javax.swing.JScrollPane();
        jListSI = new javax.swing.JList<>();
        jLabelPartidoSD = new javax.swing.JLabel();
        jLabelPartidoSI = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelVotacionProvincia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSig = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMenuVotacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneMenuVotacion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        jRadioButtonDD.setText("jRadioButtonDD");
        jRadioButtonDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDDActionPerformed(evt);
            }
        });

        jRadioButtonDI.setText("jRadioButtonDI");
        jRadioButtonDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDIActionPerformed(evt);
            }
        });

        jListDD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneDD.setViewportView(jListDD);

        jListDI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneDI.setViewportView(jListDI);

        jLabelPartidoDD.setText("Partido");

        jLabelPartidoDI.setText("Partido");

        jLayeredPaneDiputados.setLayer(jRadioButtonDD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jRadioButtonDI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jScrollPaneDD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jScrollPaneDI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jLabelPartidoDD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jLabelPartidoDI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneDiputadosLayout = new javax.swing.GroupLayout(jLayeredPaneDiputados);
        jLayeredPaneDiputados.setLayout(jLayeredPaneDiputadosLayout);
        jLayeredPaneDiputadosLayout.setHorizontalGroup(
            jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDiputadosLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDD)
                    .addComponent(jLabelPartidoDD)
                    .addComponent(jScrollPaneDD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonDI)
                    .addComponent(jLabelPartidoDI)
                    .addComponent(jScrollPaneDI, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jLayeredPaneDiputadosLayout.setVerticalGroup(
            jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDiputadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartidoDD)
                    .addComponent(jLabelPartidoDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDD, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDD)
                    .addComponent(jRadioButtonDI)))
        );

        javax.swing.GroupLayout jPanelDiputadosLayout = new javax.swing.GroupLayout(jPanelDiputados);
        jPanelDiputados.setLayout(jPanelDiputadosLayout);
        jPanelDiputadosLayout.setHorizontalGroup(
            jPanelDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiputadosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLayeredPaneDiputados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanelDiputadosLayout.setVerticalGroup(
            jPanelDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiputadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPaneDiputados)
                .addContainerGap())
        );

        jTabbedPaneMenuVotacion.addTab("Diputados", jPanelDiputados);

        jRadioButtonSD.setText("jRadioButtonDD");
        jRadioButtonSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSDActionPerformed(evt);
            }
        });

        jRadioButtonSI.setText("jRadioButtonDI");
        jRadioButtonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSIActionPerformed(evt);
            }
        });

        jListSD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSD.setViewportView(jListSD);

        jListSI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSI.setViewportView(jListSI);

        jLabelPartidoSD.setText("Partido");

        jLabelPartidoSI.setText("Partido");

        jLayeredPaneSenadores.setLayer(jRadioButtonSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jRadioButtonSI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jScrollPaneSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jScrollPaneSI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jLabelPartidoSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jLabelPartidoSI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneSenadoresLayout = new javax.swing.GroupLayout(jLayeredPaneSenadores);
        jLayeredPaneSenadores.setLayout(jLayeredPaneSenadoresLayout);
        jLayeredPaneSenadoresLayout.setHorizontalGroup(
            jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSenadoresLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPartidoSD)
                    .addComponent(jScrollPaneSD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSD))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSI)
                    .addComponent(jLabelPartidoSI)
                    .addComponent(jScrollPaneSI, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jLayeredPaneSenadoresLayout.setVerticalGroup(
            jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPartidoSD)
                    .addComponent(jLabelPartidoSI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneSD, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPaneSI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSD)
                    .addComponent(jRadioButtonSI)))
        );

        javax.swing.GroupLayout jPanelSenadoresLayout = new javax.swing.GroupLayout(jPanelSenadores);
        jPanelSenadores.setLayout(jPanelSenadoresLayout);
        jPanelSenadoresLayout.setHorizontalGroup(
            jPanelSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLayeredPaneSenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelSenadoresLayout.setVerticalGroup(
            jPanelSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPaneSenadores)
                .addContainerGap())
        );

        jTabbedPaneMenuVotacion.addTab("Senadores", jPanelSenadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jTabbedPaneMenuVotacion.addTab("Confirmacion", jPanel1);

        jLabelVotacionProvincia.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabelVotacionProvincia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVotacionProvincia.setText(" Elecciones PASO 2020 - Distrito");

        jButtonSig.setBackground(new java.awt.Color(13, 110, 253));
        jButtonSig.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonSig.setText("Siguiente");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });

        jButtonAnt.setBackground(new java.awt.Color(13, 110, 253));
        jButtonAnt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonAnt.setText("Atras");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButtonAnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSig)
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSig)
                    .addComponent(jButtonAnt))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenuVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelVotacionProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVotacionProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneMenuVotacion, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDDActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDDActionPerformed
        // TODO add your handling code here:

        if (jRadioButtonDD.isSelected()) {
            jRadioButtonDI.setSelected(false);
        }

    }//GEN-LAST:event_jRadioButtonDDActionPerformed

    private void jRadioButtonDIActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDIActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonDI.isSelected()) {
            jRadioButtonDD.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDIActionPerformed

    private void jRadioButtonSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSDActionPerformed

    private void jRadioButtonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSIActionPerformed

    private void jButtonSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        // TODO add your handling code here:

        if (jTabbedPaneMenuVotacion.getSelectedIndex() < 2) {
            int i = jTabbedPaneMenuVotacion.getSelectedIndex();
            jTabbedPaneMenuVotacion.setSelectedIndex(++i);
            this.jButtonSig.setVisible(true);
        }
        if(jTabbedPaneMenuVotacion.getSelectedIndex()==2){
            this.jButtonSig.setVisible(false);            

        }

    }//GEN-LAST:event_jButtonSigActionPerformed

    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        // TODO add your handling code here:
        
         if (jTabbedPaneMenuVotacion.getSelectedIndex() > 0) {
            int i = jTabbedPaneMenuVotacion.getSelectedIndex();
            jTabbedPaneMenuVotacion.setSelectedIndex(--i);
            this.jButtonAnt.setVisible(true);
        }
        if(jTabbedPaneMenuVotacion.getSelectedIndex()==0){
            this.jButtonAnt.setVisible(false);
        }
    }//GEN-LAST:event_jButtonAntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonEnviar1;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JLabel jLabelPartidoDD;
    private javax.swing.JLabel jLabelPartidoDI;
    private javax.swing.JLabel jLabelPartidoSD;
    private javax.swing.JLabel jLabelPartidoSI;
    private javax.swing.JLabel jLabelVotacionProvincia;
    private javax.swing.JLayeredPane jLayeredPaneDiputados;
    private javax.swing.JLayeredPane jLayeredPaneSenadores;
    private javax.swing.JList<String> jListDD;
    private javax.swing.JList<String> jListDI;
    private javax.swing.JList<String> jListSD;
    private javax.swing.JList<String> jListSI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDiputados;
    private javax.swing.JPanel jPanelSenadores;
    private javax.swing.JRadioButton jRadioButtonDD;
    private javax.swing.JRadioButton jRadioButtonDI;
    private javax.swing.JRadioButton jRadioButtonSD;
    private javax.swing.JRadioButton jRadioButtonSI;
    private javax.swing.JScrollPane jScrollPaneDD;
    private javax.swing.JScrollPane jScrollPaneDI;
    private javax.swing.JScrollPane jScrollPaneSD;
    private javax.swing.JScrollPane jScrollPaneSI;
    private javax.swing.JTabbedPane jTabbedPaneMenuVotacion;
    // End of variables declaration//GEN-END:variables

    private static List<Lista> traerListasVotante(Elector elector) {

        List<Lista> listasVotante = new ArrayList<>();

        for (int i = 0;
                i < Main.camaraElectoralArgentina.getListas().size(); i++) {

            if (Main.camaraElectoralArgentina.getListas().get(
                    i).getProvincia().equals(
                            elector.getDomicilio().getProvincia())) {

                listasVotante.add(
                        Main.camaraElectoralArgentina.getListas().get(i));
            }

        }

        return listasVotante;

    }

}
