/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.programacion_bcd.taller.vista;

import com.programacion_bcd.taller.sistema.Elector;
import com.programacion_bcd.taller.sistema.Lista;
import com.programacion_bcd.taller.sistema.Voto;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author confaa
 */
public class Votacion extends javax.swing.JFrame {

    public static List<Lista> listasVotante;

    /**
     * Creates new form Votacion
     */
    public Votacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTabbedPaneMenuVotacion.setEnabledAt(3, false);
        jButtonCancelar.setVisible(false);
        jButtonAnt.setVisible(false);
        Main mainApp = new Main();
        listasVotante = traerListasVotante(Main.elector);

        jLabelVotacionProvincia.setText(
                jLabelVotacionProvincia.getText() + " "
                + Main.elector.getDomicilio().getProvincia());
        jLabelPartidoDD.setText("Partido de Derecha");
        jLabelPartidoSD.setText("Partido de Derecha");
        jLabelPartidoDI.setText("Partido de Izquierda");
        jLabelPartidoSI.setText("Partido de Izquierda");

        jListDiputados.setModel(new DefaultListModel<>());
        jLabelPartidoD.setText("Partido: ");
        jLabelListaD.setText("Lista: ");

        jListSenadores.setModel(new DefaultListModel<>());
        jLabelPartidoS.setText("Partido: ");
        jLabelListaS.setText("Lista: ");

        for (int i = 0; i < 2; i++) {
            Lista auxLista = listasVotante.get(i);
            DefaultListModel defaultListModel1 = new DefaultListModel();
            for (int j = 0; j < auxLista.getDiputados().size(); j++) {
                defaultListModel1.addElement(
                        auxLista.getDiputados().get(j).getApellido()
                        + ", "
                        + auxLista.getDiputados().get(j).getNombre());

            }

            DefaultListModel defaultListModel2 = new DefaultListModel();
            for (int j = 0; j < auxLista.getSenadores().size(); j++) {
                defaultListModel2.addElement(
                        auxLista.getSenadores().get(j).getApellido()
                        + ", "
                        + auxLista.getSenadores().get(j).getNombre());

            }

            if (auxLista.getPartido().getNombre().equals("Derecha")) {
                jRadioButtonDD.setText(
                        "Lista " + auxLista.getNombreLista() + " - " +
                        auxLista.getNumero());
                jRadioButtonSD.setText(
                        "Lista " + auxLista.getNombreLista() + " - " +
                        auxLista.getNumero());
                jListDD.setModel(defaultListModel1);
                jListSD.setModel(defaultListModel2);

            } else {
                jRadioButtonDI.setText(
                        "Lista " + auxLista.getNombreLista() + " - " +
                        auxLista.getNumero());
                jRadioButtonSI.setText(
                        "Lista " + auxLista.getNombreLista() + " - " +
                        auxLista.getNumero());
                jListDI.setModel(defaultListModel1);
                jListSI.setModel(defaultListModel2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenuVotacion = new javax.swing.JTabbedPane();
        jPanelDiputados = new javax.swing.JPanel();
        jLayeredPaneDiputados = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabelPartidoDD = new javax.swing.JLabel();
        jScrollPaneDD = new javax.swing.JScrollPane();
        jListDD = new javax.swing.JList<>();
        jRadioButtonDD = new javax.swing.JRadioButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jRadioButtonDI = new javax.swing.JRadioButton();
        jLabelPartidoDI = new javax.swing.JLabel();
        jScrollPaneDI = new javax.swing.JScrollPane();
        jListDI = new javax.swing.JList<>();
        jPanelSenadores = new javax.swing.JPanel();
        jLayeredPaneSenadores = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jRadioButtonSI = new javax.swing.JRadioButton();
        jLabelPartidoSI = new javax.swing.JLabel();
        jScrollPaneSI = new javax.swing.JScrollPane();
        jListSI = new javax.swing.JList<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jRadioButtonSD = new javax.swing.JRadioButton();
        jLabelPartidoSD = new javax.swing.JLabel();
        jScrollPaneSD = new javax.swing.JScrollPane();
        jListSD = new javax.swing.JList<>();
        jPanelSeleccionados = new javax.swing.JPanel();
        jLayeredPaneSeleccionados = new javax.swing.JLayeredPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLabelEleccionDiputados = new javax.swing.JLabel();
        jScrollPaneDiputados = new javax.swing.JScrollPane();
        jListDiputados = new javax.swing.JList<>();
        jLabelPartidoD = new javax.swing.JLabel();
        jLabelListaD = new javax.swing.JLabel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLabelListaS = new javax.swing.JLabel();
        jLabelPartidoS = new javax.swing.JLabel();
        jScrollPaneSenadores = new javax.swing.JScrollPane();
        jListSenadores = new javax.swing.JList<>();
        jLabelEleccionSenadores = new javax.swing.JLabel();
        jPanelConfirmacion = new javax.swing.JPanel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        jButtonVotar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVotacionProvincia = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jButtonSig = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMenuVotacion.setCursor(
                new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneMenuVotacion.setFont(
                new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jTabbedPaneMenuVotacion.addMouseListener(
                new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTabbedPaneMenuVotacionMouseClicked(evt);
                    }
                });

        jPanelDiputados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDiputadosMouseClicked(evt);
            }
        });

        jLabelPartidoDD.setText("Partido 1");

        jListDD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneDD.setViewportView(jListDD);

        jRadioButtonDD.setText("jRadioButtonDD");
        jRadioButtonDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDDActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jLabelPartidoDD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPaneDD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jRadioButtonDD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(
                jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
                jLayeredPane3Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane3Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(
                                                                  jRadioButtonDD)
                                                          .addComponent(
                                                                  jLabelPartidoDD)
                                                          .addComponent(
                                                                  jScrollPaneDD,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
                jLayeredPane3Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelPartidoDD)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jScrollPaneDD,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        288, Short.MAX_VALUE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jRadioButtonDD)
                                          .addContainerGap())
        );

        jRadioButtonDI.setText("jRadioButtonDI");
        jRadioButtonDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDIActionPerformed(evt);
            }
        });

        jLabelPartidoDI.setText("Partido 2");

        jListDI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneDI.setViewportView(jListDI);

        jLayeredPane4.setLayer(jRadioButtonDI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabelPartidoDI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPaneDI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(
                jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
                jLayeredPane4Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane4Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(
                                                                  jRadioButtonDI)
                                                          .addComponent(
                                                                  jLabelPartidoDI)
                                                          .addComponent(
                                                                  jScrollPaneDI,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
                jLayeredPane4Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelPartidoDI)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jScrollPaneDI,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        288, Short.MAX_VALUE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jRadioButtonDI)
                                          .addContainerGap())
        );

        jLayeredPaneDiputados.setLayer(jLayeredPane3,
                                       javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jLayeredPane4,
                                       javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneDiputadosLayout = new javax.swing.GroupLayout(
                jLayeredPaneDiputados);
        jLayeredPaneDiputados.setLayout(jLayeredPaneDiputadosLayout);
        jLayeredPaneDiputadosLayout.setHorizontalGroup(
                jLayeredPaneDiputadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jLayeredPaneDiputadosLayout.createSequentialGroup()
                                        .addContainerGap(16, Short.MAX_VALUE)
                                        .addComponent(jLayeredPane3,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLayeredPane4,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
        );
        jLayeredPaneDiputadosLayout.setVerticalGroup(
                jLayeredPaneDiputadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jLayeredPaneDiputadosLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jLayeredPaneDiputadosLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jLayeredPane3)
                                                        .addComponent(
                                                                jLayeredPane4)))
        );

        javax.swing.GroupLayout jPanelDiputadosLayout = new javax.swing.GroupLayout(
                jPanelDiputados);
        jPanelDiputados.setLayout(jPanelDiputadosLayout);
        jPanelDiputadosLayout.setHorizontalGroup(
                jPanelDiputadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jPanelDiputadosLayout.createSequentialGroup()
                                          .addContainerGap(192, Short.MAX_VALUE)
                                          .addComponent(jLayeredPaneDiputados,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(209, 209, 209))
        );
        jPanelDiputadosLayout.setVerticalGroup(
                jPanelDiputadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jPanelDiputadosLayout.createSequentialGroup()
                                          .addContainerGap(26, Short.MAX_VALUE)
                                          .addComponent(jLayeredPaneDiputados,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(25, 25, 25))
        );

        jTabbedPaneMenuVotacion.addTab("Elección de Diputados",
                                       jPanelDiputados);

        jPanelSenadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSenadoresMouseClicked(evt);
            }
        });

        jRadioButtonSI.setText("jRadioButtonDI");
        jRadioButtonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSIActionPerformed(evt);
            }
        });

        jLabelPartidoSI.setText("Partido");

        jListSI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneSI.setViewportView(jListSI);

        jLayeredPane1.setLayer(jRadioButtonSI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabelPartidoSI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPaneSI,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(
                jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane1Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(
                                                                  jRadioButtonSI)
                                                          .addComponent(
                                                                  jLabelPartidoSI)
                                                          .addComponent(
                                                                  jScrollPaneSI,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelPartidoSI)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jScrollPaneSI,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        268, Short.MAX_VALUE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jRadioButtonSI)
                                          .addContainerGap())
        );

        jRadioButtonSD.setText("jRadioButtonDD");
        jRadioButtonSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSDActionPerformed(evt);
            }
        });

        jLabelPartidoSD.setText("Partido");

        jListSD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneSD.setViewportView(jListSD);

        jLayeredPane2.setLayer(jRadioButtonSD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabelPartidoSD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPaneSD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(
                jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
                jLayeredPane2Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane2Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(
                                                                  jLabelPartidoSD)
                                                          .addComponent(
                                                                  jScrollPaneSD,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                          .addComponent(
                                                                  jRadioButtonSD))
                                          .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
                jLayeredPane2Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelPartidoSD)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jScrollPaneSD,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        268, Short.MAX_VALUE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jRadioButtonSD)
                                          .addContainerGap())
        );

        jLayeredPaneSenadores.setLayer(jLayeredPane1,
                                       javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jLayeredPane2,
                                       javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneSenadoresLayout = new javax.swing.GroupLayout(
                jLayeredPaneSenadores);
        jLayeredPaneSenadores.setLayout(jLayeredPaneSenadoresLayout);
        jLayeredPaneSenadoresLayout.setHorizontalGroup(
                jLayeredPaneSenadoresLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jLayeredPaneSenadoresLayout.createSequentialGroup()
                                        .addContainerGap(73, Short.MAX_VALUE)
                                        .addComponent(jLayeredPane2,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane1,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
        );
        jLayeredPaneSenadoresLayout.setVerticalGroup(
                jLayeredPaneSenadoresLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jLayeredPaneSenadoresLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jLayeredPaneSenadoresLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jLayeredPane1)
                                                        .addComponent(
                                                                jLayeredPane2)))
        );

        javax.swing.GroupLayout jPanelSenadoresLayout = new javax.swing.GroupLayout(
                jPanelSenadores);
        jPanelSenadores.setLayout(jPanelSenadoresLayout);
        jPanelSenadoresLayout.setHorizontalGroup(
                jPanelSenadoresLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jLayeredPaneSenadores,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );
        jPanelSenadoresLayout.setVerticalGroup(
                jPanelSenadoresLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jLayeredPaneSenadores,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );

        jTabbedPaneMenuVotacion.addTab("Elección de Senadores",
                                       jPanelSenadores);

        jPanelSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSeleccionadosMouseClicked(evt);
            }
        });

        jLabelEleccionDiputados.setFont(
                new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelEleccionDiputados.setText("Elección Diputados: ");

        jListDiputados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneDiputados.setViewportView(jListDiputados);

        jLabelPartidoD.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelPartidoD.setText("jLabel3");

        jLabelListaD.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelListaD.setText("jLabel3");

        jLayeredPane7.setLayer(jLabelEleccionDiputados,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jScrollPaneDiputados,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabelPartidoD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane7.setLayer(jLabelListaD,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(
                jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
                jLayeredPane7Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane7Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane7Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING,
                                                                  false)
                                                          .addComponent(
                                                                  jScrollPaneDiputados)
                                                          .addComponent(
                                                                  jLabelPartidoD)
                                                          .addComponent(
                                                                  jLabelListaD)
                                                          .addComponent(
                                                                  jLabelEleccionDiputados,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );
        jLayeredPane7Layout.setVerticalGroup(
                jLayeredPane7Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane7Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelEleccionDiputados)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabelPartidoD)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabelListaD)
                                          .addGap(18, 18, 18)
                                          .addComponent(jScrollPaneDiputados,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        231,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap())
        );

        jLabelListaS.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelListaS.setText("jLabel4");

        jLabelPartidoS.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelPartidoS.setText("jLabel4");

        jListSenadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {return strings.length;}

            public String getElementAt(int i) {return strings[i];}
        });
        jScrollPaneSenadores.setViewportView(jListSenadores);

        jLabelEleccionSenadores.setFont(
                new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelEleccionSenadores.setText("Elección Senadores: ");

        jLayeredPane8.setLayer(jLabelListaS,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabelPartidoS,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jScrollPaneSenadores,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabelEleccionSenadores,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(
                jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
                jLayeredPane8Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane8Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane8Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING,
                                                                  false)
                                                          .addComponent(
                                                                  jLabelPartidoS)
                                                          .addComponent(
                                                                  jLabelListaS)
                                                          .addComponent(
                                                                  jScrollPaneSenadores)
                                                          .addComponent(
                                                                  jLabelEleccionSenadores,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  300,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );
        jLayeredPane8Layout.setVerticalGroup(
                jLayeredPane8Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane8Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelEleccionSenadores)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabelPartidoS)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabelListaS)
                                          .addGap(18, 18, 18)
                                          .addComponent(jScrollPaneSenadores,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        231,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap())
        );

        jLayeredPaneSeleccionados.setLayer(jLayeredPane7,
                                           javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSeleccionados.setLayer(jLayeredPane8,
                                           javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneSeleccionadosLayout = new javax.swing.GroupLayout(
                jLayeredPaneSeleccionados);
        jLayeredPaneSeleccionados.setLayout(jLayeredPaneSeleccionadosLayout);
        jLayeredPaneSeleccionadosLayout.setHorizontalGroup(
                jLayeredPaneSeleccionadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jLayeredPaneSeleccionadosLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLayeredPane7,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLayeredPane8,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(290, Short.MAX_VALUE))
        );
        jLayeredPaneSeleccionadosLayout.setVerticalGroup(
                jLayeredPaneSeleccionadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jLayeredPaneSeleccionadosLayout.createSequentialGroup()
                                          .addContainerGap(19, Short.MAX_VALUE)
                                          .addGroup(
                                                  jLayeredPaneSeleccionadosLayout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.TRAILING)
                                                          .addComponent(
                                                                  jLayeredPane8,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                                                          .addComponent(
                                                                  jLayeredPane7,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSeleccionadosLayout = new javax.swing.GroupLayout(
                jPanelSeleccionados);
        jPanelSeleccionados.setLayout(jPanelSeleccionadosLayout);
        jPanelSeleccionadosLayout.setHorizontalGroup(
                jPanelSeleccionadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanelSeleccionadosLayout.createSequentialGroup()
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLayeredPaneSeleccionados)
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
        );
        jPanelSeleccionadosLayout.setVerticalGroup(
                jPanelSeleccionadosLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jPanelSeleccionadosLayout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(
                                                  jLayeredPaneSeleccionados)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );

        jTabbedPaneMenuVotacion.addTab("Candidatos Seleccionados",
                                       jPanelSeleccionados);

        jPanelConfirmacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConfirmacionMouseClicked(evt);
            }
        });

        jButtonVotar.setBackground(new java.awt.Color(40, 167, 69));
        jButtonVotar.setFont(new java.awt.Font("Roboto", 0, 72)); // NOI18N
        jButtonVotar.setText("Votar");
        jButtonVotar.setHorizontalTextPosition(
                javax.swing.SwingConstants.CENTER);
        jButtonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVotarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(220, 53, 69));
        jButtonCancelar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonCancelar.setText("Reset");
        jButtonCancelar.setHorizontalTextPosition(
                javax.swing.SwingConstants.CENTER);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(jButtonCancelar);
        jLabel1.setText("Desea elegir nuevamente los candidatos?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(jButtonVotar);
        jLabel2.setText("Confirmar voto");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLayeredPane6.setLayer(jButtonVotar,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jButtonCancelar,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(
                jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
                jLayeredPane6Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jLayeredPane6Layout.createSequentialGroup()
                                          .addGap(0, 0, Short.MAX_VALUE)
                                          .addGroup(
                                                  jLayeredPane6Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.LEADING)
                                                          .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                          .addComponent(jLabel2,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        278,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                          .addGap(93, 93, 93)
                                          .addComponent(jButtonCancelar)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jLayeredPane6Layout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jButtonVotar)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
                jLayeredPane6Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane6Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabel2)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                  18, Short.MAX_VALUE)
                                          .addComponent(jButtonVotar)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jLabel1)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addComponent(jButtonCancelar)
                                          .addContainerGap())
        );

        javax.swing.GroupLayout jPanelConfirmacionLayout = new javax.swing.GroupLayout(
                jPanelConfirmacion);
        jPanelConfirmacion.setLayout(jPanelConfirmacionLayout);
        jPanelConfirmacionLayout.setHorizontalGroup(
                jPanelConfirmacionLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanelConfirmacionLayout.createSequentialGroup()
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLayeredPane6,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                                      javax.swing.GroupLayout.DEFAULT_SIZE,
                                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
        );
        jPanelConfirmacionLayout.setVerticalGroup(
                jPanelConfirmacionLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jPanelConfirmacionLayout.createSequentialGroup()
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jLayeredPane6,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addContainerGap(
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE))
        );

        jTabbedPaneMenuVotacion.addTab("Confirmación Voto", jPanelConfirmacion);

        jLabelVotacionProvincia.setFont(
                new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabelVotacionProvincia.setHorizontalAlignment(
                javax.swing.SwingConstants.CENTER);
        jLabelVotacionProvincia.setText(" Elecciones PASO 2021 - Distrito");

        jButtonSig.setBackground(new java.awt.Color(13, 110, 253));
        jButtonSig.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonSig.setText("Siguiente");
        jButtonSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSigActionPerformed(evt);
            }
        });

        jButtonAnt.setBackground(new java.awt.Color(13, 110, 253));
        jButtonAnt.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonAnt.setText("Atras");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jButtonSig,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jButtonAnt,
                               javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(
                jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
                jLayeredPane5Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jButtonAnt)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                  Short.MAX_VALUE)
                                          .addComponent(jButtonSig)
                                          .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
                jLayeredPane5Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane5Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                  jLayeredPane5Layout.createParallelGroup(
                                                                  javax.swing.GroupLayout.Alignment.BASELINE)
                                                          .addComponent(
                                                                  jButtonSig)
                                                          .addComponent(
                                                                  jButtonAnt))
                                          .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(
                jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
                jPanelBotonesLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelBotonesLayout.createSequentialGroup()
                                          .addGap(79, 79, 79)
                                          .addComponent(jLayeredPane5)
                                          .addGap(89, 89, 89))
        );
        jPanelBotonesLayout.setVerticalGroup(
                jPanelBotonesLayout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  jPanelBotonesLayout.createSequentialGroup()
                                          .addContainerGap(45, Short.MAX_VALUE)
                                          .addComponent(jLayeredPane5,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPaneMenuVotacion)
                        .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(
                                                          javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(
                                                                    jPanelBotones,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE)
                                                            .addComponent(
                                                                    jLabelVotacionProvincia,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                    Short.MAX_VALUE))
                                          .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                  layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(jLabelVotacionProvincia,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        71,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jTabbedPaneMenuVotacion,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        455,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(
                                                  javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(jPanelBotones,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDDActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDDActionPerformed
        // TODO add your handling code here:

        if (jRadioButtonDD.isSelected()) {
            jRadioButtonDI.setSelected(false);
            jListDiputados.setModel(jListDD.getModel());
            jLabelPartidoD.setText("Partido: " + jLabelPartidoDD.getText());
            jLabelListaD.setText("Lista: " + jRadioButtonDD.getText());
        } else {
            jListDiputados.setModel(new DefaultListModel<>());
            jLabelPartidoD.setText("Partido: ");
            jLabelListaD.setText("Lista: ");
        }

    }//GEN-LAST:event_jRadioButtonDDActionPerformed

    private void jRadioButtonDIActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDIActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonDI.isSelected()) {
            jRadioButtonDD.setSelected(false);
            jListDiputados.setModel(jListDI.getModel());
            jLabelPartidoD.setText("Partido: " + jLabelPartidoDI.getText());
            jLabelListaD.setText("Lista: " + jRadioButtonDI.getText());
        } else {
            jListDiputados.setModel(new DefaultListModel<>());
            jLabelPartidoD.setText("Partido: ");
            jLabelListaD.setText("Lista: ");
        }

    }//GEN-LAST:event_jRadioButtonDIActionPerformed

    private void jRadioButtonSDActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSDActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonSD.isSelected()) {
            jRadioButtonSI.setSelected(false);
            jListSenadores.setModel(jListSD.getModel());
            jLabelPartidoS.setText("Partido: " + jLabelPartidoSD.getText());
            jLabelListaS.setText("Lista: " + jRadioButtonSD.getText());
        } else {
            jListDiputados.setModel(new DefaultListModel<>());
            jLabelPartidoS.setText("Partido: ");
            jLabelListaS.setText("Lista: ");
        }

    }//GEN-LAST:event_jRadioButtonSDActionPerformed

    private void jRadioButtonSIActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSIActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonSI.isSelected()) {
            jRadioButtonSD.setSelected(false);
            jListSenadores.setModel(jListSI.getModel());
            jLabelPartidoS.setText("Partido: " + jLabelPartidoSI.getText());
            jLabelListaS.setText("Lista: " + jRadioButtonSI.getText());
        } else {
            jListSenadores.setModel(new DefaultListModel<>());
            jLabelPartidoS.setText("Partido: ");
            jLabelListaS.setText("Lista: ");
        }

    }//GEN-LAST:event_jRadioButtonSIActionPerformed

    private void jButtonSigActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSigActionPerformed
        // TODO add your handling code here:

        if (jTabbedPaneMenuVotacion.getSelectedIndex() < 3) {
            int i = jTabbedPaneMenuVotacion.getSelectedIndex();
            jTabbedPaneMenuVotacion.setSelectedIndex(++i);
            this.jButtonSig.setVisible(true);
        }
        if (jTabbedPaneMenuVotacion.getSelectedIndex() == 3) {
            this.jButtonSig.setVisible(false);
            this.jButtonCancelar.setVisible(true);
            this.jButtonVotar.setVisible(true);
            this.jButtonAnt.setVisible(false);
            this.jTabbedPaneMenuVotacion.setEnabledAt(0, false);
            this.jTabbedPaneMenuVotacion.setEnabledAt(1, false);
            this.jTabbedPaneMenuVotacion.setEnabledAt(2, false);
            this.jTabbedPaneMenuVotacion.setEnabledAt(3, true);

        } else if (jTabbedPaneMenuVotacion.getSelectedIndex() == 1) {
            this.jButtonAnt.setVisible(true);
        }

    }//GEN-LAST:event_jButtonSigActionPerformed

    private void jButtonAntActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        // TODO add your handling code here:

        if (jTabbedPaneMenuVotacion.getSelectedIndex() > 0) {
            int i = jTabbedPaneMenuVotacion.getSelectedIndex();
            jTabbedPaneMenuVotacion.setSelectedIndex(--i);
            this.jButtonAnt.setVisible(true);
        }
        if (jTabbedPaneMenuVotacion.getSelectedIndex() == 0) {
            this.jButtonAnt.setVisible(false);
        } else if (jTabbedPaneMenuVotacion.getSelectedIndex() == 2) {
            this.jButtonSig.setVisible(true);

        }
        this.jButtonCancelar.setVisible(false);
        this.jButtonVotar.setVisible(false);
    }//GEN-LAST:event_jButtonAntActionPerformed

    private void jButtonVotarActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVotarActionPerformed
        // TODO add your handling code here:

        String diputados = "";
        String senadores = "";
        int indice = 0;
        if (jRadioButtonDD.isSelected()) {
            indice = jRadioButtonDD.getText().lastIndexOf(" ");
            diputados = jRadioButtonDD.getText().substring(indice + 1,
                                                           jRadioButtonDD.getText().length());

        } else if (jRadioButtonDI.isSelected()) {
            indice = jRadioButtonDI.getText().lastIndexOf(" ");
            diputados = jRadioButtonDI.getText().substring(indice + 1,
                                                           jRadioButtonDI.getText().length());
        }
        Lista listaDiputados;
        if (diputados.equals("")) {
            listaDiputados = new Lista("", "", "", null, null, null, null,
                                       null);
        } else {
            listaDiputados = traerListaVotada(diputados);
        }

        if (jRadioButtonSD.isSelected()) {
            indice = jRadioButtonSD.getText().lastIndexOf(" ");
            senadores = jRadioButtonSD.getText().substring(indice + 1,
                                                           jRadioButtonSD.getText().length());

        } else if (jRadioButtonSI.isSelected()) {
            indice = jRadioButtonSI.getText().lastIndexOf(" ");
            senadores = jRadioButtonSI.getText().substring(indice + 1,
                                                           jRadioButtonSI.getText().length());
        }

        System.out.println(senadores);
        Lista listaSenadores;
        if (senadores.equals("")) {
            listaSenadores = new Lista("", "", "", null, null, null, null,
                                       null);
        } else {
            listaSenadores = traerListaVotada(senadores);
        }

        Voto voto = new Voto(
                Main.elector,
                Main.elector.getMesa(), listaDiputados,
                listaSenadores);

        Main.elector.setVoto(voto);

        for (int z = 0;
             z < Main.camaraElectoralArgentina.getListas().size(); z++) {

            if (Main.camaraElectoralArgentina.getListas().get(z).equals(
                    diputados)) {
                Main.camaraElectoralArgentina.getListas().get(
                        z).getVotoDiputados().add(voto);

            }
            if (Main.camaraElectoralArgentina.getListas().get(z).equals(
                    senadores)) {
                Main.camaraElectoralArgentina.getListas().get(
                        z).getVotoSenadores().add(voto);
            }

        }
        this.setVisible(false);
        Main main = new Main();
        main.setVisible(true);

    }//GEN-LAST:event_jButtonVotarActionPerformed

    private void jPanelConfirmacionMouseClicked(
            java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConfirmacionMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelConfirmacionMouseClicked

    private void jTabbedPaneMenuVotacionMouseClicked(
            java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMenuVotacionMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPaneMenuVotacionMouseClicked

    private void jButtonCancelarActionPerformed(
            java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jListDiputados.setModel(new DefaultListModel<>());
        jLabelPartidoD.setText("Partido: ");
        jLabelListaD.setText("Lista: ");
        jListSenadores.setModel(new DefaultListModel<>());
        jLabelPartidoS.setText("Partido: ");
        jLabelListaS.setText("Lista: ");
        jRadioButtonDD.setSelected(false);
        jRadioButtonSD.setSelected(false);
        jRadioButtonDI.setSelected(false);
        jRadioButtonSI.setSelected(false);
        this.jTabbedPaneMenuVotacion.setEnabledAt(0, true);
        this.jTabbedPaneMenuVotacion.setEnabledAt(1, true);
        this.jTabbedPaneMenuVotacion.setEnabledAt(2, true);
        this.jTabbedPaneMenuVotacion.setEnabledAt(3, false);
        this.jTabbedPaneMenuVotacion.setSelectedIndex(0);
        this.jButtonSig.setVisible(true);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPanelDiputadosMouseClicked(
            java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDiputadosMouseClicked
        // TODO add your handling code here:

        ;
    }//GEN-LAST:event_jPanelDiputadosMouseClicked

    private void jPanelSenadoresMouseClicked(
            java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSenadoresMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelSenadoresMouseClicked

    private void jPanelSeleccionadosMouseClicked(
            java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSeleccionadosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelSeleccionadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSig;
    private javax.swing.JButton jButtonVotar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEleccionDiputados;
    private javax.swing.JLabel jLabelEleccionSenadores;
    private javax.swing.JLabel jLabelListaD;
    private javax.swing.JLabel jLabelListaS;
    private javax.swing.JLabel jLabelPartidoD;
    private javax.swing.JLabel jLabelPartidoDD;
    private javax.swing.JLabel jLabelPartidoDI;
    private javax.swing.JLabel jLabelPartidoS;
    private javax.swing.JLabel jLabelPartidoSD;
    private javax.swing.JLabel jLabelPartidoSI;
    private javax.swing.JLabel jLabelVotacionProvincia;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPaneDiputados;
    private javax.swing.JLayeredPane jLayeredPaneSeleccionados;
    private javax.swing.JLayeredPane jLayeredPaneSenadores;
    private javax.swing.JList<String> jListDD;
    private javax.swing.JList<String> jListDI;
    private javax.swing.JList<String> jListDiputados;
    private javax.swing.JList<String> jListSD;
    private javax.swing.JList<String> jListSI;
    private javax.swing.JList<String> jListSenadores;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelConfirmacion;
    private javax.swing.JPanel jPanelDiputados;
    private javax.swing.JPanel jPanelSeleccionados;
    private javax.swing.JPanel jPanelSenadores;
    private javax.swing.JRadioButton jRadioButtonDD;
    private javax.swing.JRadioButton jRadioButtonDI;
    private javax.swing.JRadioButton jRadioButtonSD;
    private javax.swing.JRadioButton jRadioButtonSI;
    private javax.swing.JScrollPane jScrollPaneDD;
    private javax.swing.JScrollPane jScrollPaneDI;
    private javax.swing.JScrollPane jScrollPaneDiputados;
    private javax.swing.JScrollPane jScrollPaneSD;
    private javax.swing.JScrollPane jScrollPaneSI;
    private javax.swing.JScrollPane jScrollPaneSenadores;
    private javax.swing.JTabbedPane jTabbedPaneMenuVotacion;
    // End of variables declaration//GEN-END:variables

    private static List<Lista> traerListasVotante(Elector elector) {

        List<Lista> listasVotante = new ArrayList<>();

        for (int i = 0;
             i < Main.camaraElectoralArgentina.getListas().size(); i++) {

            if (Main.camaraElectoralArgentina.getListas().get(
                    i).getProvincia().equals(
                    elector.getDomicilio().getProvincia())) {

                listasVotante.add(
                        Main.camaraElectoralArgentina.getListas().get(i));
            }

        }

        return listasVotante;

    }

    public static Lista traerListaVotada(String numeroLista) {
        Lista retorno = new Lista("", "", numeroLista, null, null, null, null,
                                  null);

        for (int i = 0;
             i < Main.camaraElectoralArgentina.getListas().size(); i++) {

            if (Main.camaraElectoralArgentina.getListas().get(i).equals(
                    retorno)) {
                retorno = Main.camaraElectoralArgentina.getListas().get(i);
                break;

            }
        }
        return retorno;

    }

}
