/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.programacion_bcd.taller.vista;

/**
 *
 * @author confaa
 */
public class Votacion extends javax.swing.JFrame {

    /**
     * Creates new form Votacion
     */
    public Votacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Main main=new Main();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMenuPrincipal = new javax.swing.JTabbedPane();
        jPanelDiputados = new javax.swing.JPanel();
        jLayeredPaneDiputados = new javax.swing.JLayeredPane();
        jRadioButtonDD = new javax.swing.JRadioButton();
        jRadioButtonDI = new javax.swing.JRadioButton();
        jScrollPaneDD = new javax.swing.JScrollPane();
        jListDD = new javax.swing.JList<>();
        jScrollPaneDI = new javax.swing.JScrollPane();
        jListDI = new javax.swing.JList<>();
        jPanelSenadores = new javax.swing.JPanel();
        jLayeredPaneSenadores = new javax.swing.JLayeredPane();
        jRadioButtonSD = new javax.swing.JRadioButton();
        jRadioButtonSI = new javax.swing.JRadioButton();
        jScrollPaneSD = new javax.swing.JScrollPane();
        jListSD = new javax.swing.JList<>();
        jScrollPaneSI = new javax.swing.JScrollPane();
        jListSI = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMenuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPaneMenuPrincipal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N

        jRadioButtonDD.setText("jRadioButtonDD");
        jRadioButtonDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDDActionPerformed(evt);
            }
        });

        jRadioButtonDI.setText("jRadioButtonDI");
        jRadioButtonDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDIActionPerformed(evt);
            }
        });

        jListDD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneDD.setViewportView(jListDD);

        jListDI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneDI.setViewportView(jListDI);

        jLayeredPaneDiputados.setLayer(jRadioButtonDD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jRadioButtonDI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jScrollPaneDD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDiputados.setLayer(jScrollPaneDI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneDiputadosLayout = new javax.swing.GroupLayout(jLayeredPaneDiputados);
        jLayeredPaneDiputados.setLayout(jLayeredPaneDiputadosLayout);
        jLayeredPaneDiputadosLayout.setHorizontalGroup(
            jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDiputadosLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonDI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDI))
                .addGap(195, 195, 195))
        );
        jLayeredPaneDiputadosLayout.setVerticalGroup(
            jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDiputadosLayout.createSequentialGroup()
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneDiputadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jLayeredPaneDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDD)
                    .addComponent(jRadioButtonDI)))
        );

        javax.swing.GroupLayout jPanelDiputadosLayout = new javax.swing.GroupLayout(jPanelDiputados);
        jPanelDiputados.setLayout(jPanelDiputadosLayout);
        jPanelDiputadosLayout.setHorizontalGroup(
            jPanelDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiputadosLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLayeredPaneDiputados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanelDiputadosLayout.setVerticalGroup(
            jPanelDiputadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiputadosLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLayeredPaneDiputados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPaneMenuPrincipal.addTab("Diputados", jPanelDiputados);

        jRadioButtonSD.setText("jRadioButtonDD");
        jRadioButtonSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSDActionPerformed(evt);
            }
        });

        jRadioButtonSI.setText("jRadioButtonDI");
        jRadioButtonSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSIActionPerformed(evt);
            }
        });

        jListSD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSD.setViewportView(jListSD);

        jListSI.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneSI.setViewportView(jListSI);

        jLayeredPaneSenadores.setLayer(jRadioButtonSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jRadioButtonSI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jScrollPaneSD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneSenadores.setLayer(jScrollPaneSI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneSenadoresLayout = new javax.swing.GroupLayout(jLayeredPaneSenadores);
        jLayeredPaneSenadores.setLayout(jLayeredPaneSenadoresLayout);
        jLayeredPaneSenadoresLayout.setHorizontalGroup(
            jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSenadoresLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneSD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonSI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneSI))
                .addGap(195, 195, 195))
        );
        jLayeredPaneSenadoresLayout.setVerticalGroup(
            jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneSenadoresLayout.createSequentialGroup()
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneSenadoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jLayeredPaneSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSD)
                    .addComponent(jRadioButtonSI)))
        );

        javax.swing.GroupLayout jPanelSenadoresLayout = new javax.swing.GroupLayout(jPanelSenadores);
        jPanelSenadores.setLayout(jPanelSenadoresLayout);
        jPanelSenadoresLayout.setHorizontalGroup(
            jPanelSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLayeredPaneSenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanelSenadoresLayout.setVerticalGroup(
            jPanelSenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenadoresLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLayeredPaneSenadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPaneMenuPrincipal.addTab("Senadores", jPanelSenadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDDActionPerformed
        // TODO add your handling code here:
         
        if(jRadioButtonDD.isSelected()){
            jRadioButtonDI.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonDDActionPerformed

    private void jRadioButtonDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDIActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonDI.isSelected()){
            jRadioButtonDD.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDIActionPerformed

    private void jRadioButtonSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSDActionPerformed

    private void jRadioButtonSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Votacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Votacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPaneDiputados;
    private javax.swing.JLayeredPane jLayeredPaneSenadores;
    private javax.swing.JList<String> jListDD;
    private javax.swing.JList<String> jListDI;
    private javax.swing.JList<String> jListSD;
    private javax.swing.JList<String> jListSI;
    private javax.swing.JPanel jPanelDiputados;
    private javax.swing.JPanel jPanelSenadores;
    private javax.swing.JRadioButton jRadioButtonDD;
    private javax.swing.JRadioButton jRadioButtonDI;
    private javax.swing.JRadioButton jRadioButtonSD;
    private javax.swing.JRadioButton jRadioButtonSI;
    private javax.swing.JScrollPane jScrollPaneDD;
    private javax.swing.JScrollPane jScrollPaneDI;
    private javax.swing.JScrollPane jScrollPaneSD;
    private javax.swing.JScrollPane jScrollPaneSI;
    private javax.swing.JTabbedPane jTabbedPaneMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
